train:
  _target_: src.datasets.ASVspoof2019LADataset
  root_dir: ${oc.env:ASVSPOOF_LA_ROOT,./data/ASVspoof2019_LA}
  partition: train
  balanced_sampling: true
  feature_extractor:
    _target_: src.transforms.LogPowerSpectrogram
    sample_rate: 16000
    n_fft: 1724
    win_length: 1724
    hop_seconds: 0.0081
    max_frames: 600
    crop_mode: start
    short_input_mode: repeat
    center: true
  instance_transforms: ${transforms.instance_transforms.train}

dev:
  _target_: src.datasets.ASVspoof2019LADataset
  root_dir: ${oc.env:ASVSPOOF_LA_ROOT,./data/ASVspoof2019_LA}
  partition: dev
  feature_extractor:
    _target_: src.transforms.LogPowerSpectrogram
    sample_rate: 16000
    n_fft: 1724
    win_length: 1724
    hop_seconds: 0.0081
    max_frames: 600
    crop_mode: start
    short_input_mode: repeat
    center: true
  instance_transforms: ${transforms.instance_transforms.inference}
