defaults:
  - lcnn
  - override datasets: asvspoof_la_onebatch
  - _self_

trainer:
  n_epochs: 100
  epoch_len: 1
  log_step: 1
  use_amp: false
  monitor: "min dev_EER"
  save_period: 25
  early_stop: 100
  override: false

dataloader:
  batch_size: 8
  num_workers: 0
  pin_memory: false
  persistent_workers: false

writer:
  run_name: lcnn_onebatch
  mode: offline
